[package]
authors = ["Mankong Zhao <mankong.zhao@aax.com>"]
edition = "2018"
name = "siwi-download"
version = "0.2.0"
license = "MIT"
description = "async download file"
repository = "https://github.com/rs-videos/siwi-download.git"
documentation = "https://docs.rs/siwi-download"
categories = [
  "download",
  "async download",
  "http range download"
]
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
docs = ["unstable"]
unstable = []

[dependencies]
anyhow = "1"
chrono = "0.4"
indicatif = "0.15"
reqwest = {version = "0.11", default-features = false, features = ["rustls-tls", "json"]}
tokio = {version = "1", features = ["fs", "macros", "rt-multi-thread"]}
