[package]
authors = ["Mankong <mankong@mankong.me>", "siwilizhao <siwilizhao@gmail.com>"]
categories = ["filesystem", "command-line-interface"]
description = "Downloader with a pure http implementation support breakpoint continuations"
documentation = "https://docs.rs/siwi-download"
edition = "2024"
keywords = ["siwi-download", "download", "siwi", "downloader"]
license = "MIT"
name = "siwi-download"
readme = "README.md"
repository = "https://github.com/rs-videos/siwi-download.git"
version = "0.4.3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
docs = ["unstable"]
unstable = []

[dependencies]
anyhow = "^1.0.100"
chrono = {version = "^0.4.42", features = ["serde"]}
indicatif = "^0.18.3"
reqwest = {version = "^0.13.1", default-features = false, features = [
  "rustls",
  "json",
]}
serde = {version = "^1.0.228", features = ["derive"]}
serde_json = "^1.0.149"
tokio = {version = "^1.49.0", features = ["fs", "macros", "rt-multi-thread", "io-util"]}
tracing = "^0.1.44"
tracing-subscriber = "^0.3.22"

[[example]]
name = "cli"
path = "examples/cli.rs"

[[example]]
name = "download"
path = "examples/download.rs"
