[package]
authors = ["Mankong Zhao <mankong.zhao@aax.com>"]
categories = [
  "download",
  "downloader",
]
description = "async download file"
documentation = "https://docs.rs/siwi-download"
edition = "2018"
license = "MIT"
name = "siwi-download"
readme = "README.md"
repository = "https://github.com/rs-videos/siwi-download.git"
version = "0.2.3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
docs = ["unstable"]
unstable = []

[dependencies]
anyhow = "1"
chrono = "0.4"
indicatif = "0.15"
log = "0.4"
reqwest = {version = "0.11", default-features = false, features = ["rustls-tls", "json"]}
tokio = {version = "1", features = ["fs", "macros", "rt-multi-thread"]}
